IMP: ./anydbver Samba AD + mysql

diff --git a/anydbver b/anydbver
--- a/anydbver
+++ b/anydbver
@@ -25,6 +25,7 @@ if [ "x$2" = "xhelp" ] ; then
     echo "$0 deploy deploy ldap node1 ldap-master:default ps:5.7"
     echo "$0 deploy ps:5.7 node1 ps:5.7 master:default node2 ps:5.7 master:node1"
     echo "$0 deploy ps:8.0 utf8 node1 ps:5.7 master:default node2 ps:5.6 master:node1 row"
+    echo "$0 deploy samba node1 ps samba-dc:default"
     echo "$0 deploy pxc:5.7 node1 pxc:5.7 galera-master:default node2 pxc:5.7 galera-master:default"
     echo "$0 deploy ps:8.0 group-replication node1 ps:8.0 group-replication master:default node2 ps:8.0 group-replication master:default"
     echo "$0 deploy k3s node1 k3s-master:default node2 k3s-master:default node3 k3s-master:default"
@@ -406,6 +407,17 @@ deploy_node() {
         DEP_ENV="$DEP_ENV DB_IP=default REPLICATION_TYPE=galera "
       fi
     fi
+    if [[ $i == "samba-ad" ]] || [[ $i == "samba" ]] ; then
+        DEP_ENV="$DEP_ENV SAMBA_AD=1 "
+    fi
+    if [[ $i == "samba-dc:"* ]] ; then
+      if [[ $i == *':'* ]] || [[ $i == *'='* ]] ; then
+        MASTER_NODE=$(get_version "$i")
+        DEP_ENV="$DEP_ENV SAMBA_IP=$MASTER_NODE SAMBA_PASS=\"verysecretpassword1^\" DB_USER=dba DB_PASS=secret "
+      else
+        DEP_ENV="$DEP_ENV SAMBA_IP=default "
+      fi
+    fi
     if [[ $i == "rbr" ]] || [[ $i == "row" ]] || [[ $i == "row-based-replication" ]] || [[ $i == "row_based_replication" ]] ; then
       ROW_REPLICATION=1
     fi
@@ -527,6 +539,29 @@ find_node_ip() {
   esac
 }
 
+find_samba_sid() {
+  NODE="$1"
+  SAMBA_IP=$(find_node_ip $NODE)
+  case "$PROVIDER" in
+    vagrant)
+      vagrant ssh $NODE -- "/opt/samba/bin/wbinfo -D PERCONA|grep SID|awk '{print \$3}'" 2>/dev/null
+      ;;
+    lxdock)
+      lxdock shell $NODE -c bash -c "/opt/samba/bin/wbinfo -D PERCONA|grep SID|awk '{print \$3}'" 2>/dev/null
+      ;;
+    podman)
+      ssh -i secret/id_rsa root@$SAMBA_IP -o StrictHostKeyChecking=no /opt/samba/bin/wbinfo -D PERCONA|grep SID|awk '{print $3}' 2>/dev/null
+      ;;
+    lxd)
+      ssh -i secret/id_rsa root@$SAMBA_IP -o StrictHostKeyChecking=no /opt/samba/bin/wbinfo -D PERCONA|grep SID|awk '{print $3}' 2>/dev/null
+      ;;
+    *)
+      echo "Please select VM/Container provider with $0 config provider:PROVIDERNAME"
+      exit 1
+  esac
+}
+
+
 find_node_token() {
   NODE="$1"
   case "$PROVIDER" in
@@ -563,7 +598,7 @@ if [ "x$1" = "xdeploy" ] ; then
       shift
     done
     DEPCMD=$(deploy_node $NODE "${DEPLARGS[@]}")
-    echo "$DEPCMD"|egrep -q 'PMM_SERVER|K8S|K3S|PKO' && PRIV_CONTAINER_REQUIRED=1
+    echo "$DEPCMD"|egrep -q 'PMM_SERVER|K8S|K3S|PKO|SAMBA_AD' && PRIV_CONTAINER_REQUIRED=1
     DEPLOY_CMDS+=("$DEPCMD")
     ALL_NODES[$NODE]=1
     if [[ "$1" == node* || "$1" == default ]] ; then
@@ -612,6 +647,12 @@ if [ "x$1" = "xdeploy" ] ; then
       MASTER_IP=$(find_node_ip $MASTER_NODE)
       MASTER_TOKEN=$(find_node_token $MASTER_NODE)
       i=$(echo "$i"|sed -e "s,K3S_URL=$MASTER_NODE,K3S_URL=https://$MASTER_IP:6443 K3S_TOKEN=$MASTER_TOKEN,g")
+    fi
+    if echo "$i" | grep -q SAMBA_IP ; then
+      MASTER_NODE=$(echo "$i" | perl -ne '/SAMBA_IP=(\S*) / and print $1')
+      MASTER_IP=$(find_node_ip $MASTER_NODE)
+      SAMBA_SID=$(find_samba_sid $MASTER_NODE)
+      i=$(echo "$i"|sed -e "s/SAMBA_IP=$MASTER_NODE/SAMBA_IP=$MASTER_IP SAMBA_SID=$SAMBA_SID/g")
     fi
 
     printf "%s\n" "$i"
